### ISSUE TITLE
TS rule conflict

### ISSUE THREAD

**Issue by crisfcodes** [kentcdodds/eslint-config-kentcdodds#103]
https://github.com/kentcdodds/eslint-config-kentcdodds/blob/4858d1e0b2d5d9e0c376175f80dc31d50691997b/best-practices.js#L188

This rule detects when an as cast is doing the same job as a `!` would, and suggests fixing the code to be an `!`.

But if you try to use `!`, this other rule will complain: 

https://github.com/kentcdodds/eslint-config-kentcdodds/blob/4858d1e0b2d5d9e0c376175f80dc31d50691997b/stylistic.js#L84

**Comment by kentcdodds** [comment]
I've bumped into this as well. Thanks!
