### ISSUE TITLE
jest/testing rules are executed in tsx files 

### ISSUE THREAD

**Issue by crisfcodes** [kentcdodds/eslint-config-kentcdodds#107]
It's normal or intentional to run `jest` and `testing-library` rules in tsx component files?

![config-error](https://user-images.githubusercontent.com/20000951/120577185-946e8780-c3e9-11eb-90bd-c81f226b7b6a.png)

**Comment by kentcdodds** [comment]
We're working on this kinda: https://github.com/kentcdodds/eslint-config-kentcdodds/pull/98

**Comment by crisfcodes** [comment]
@kentcdodds other thing is every first import thrown, this happend in all files:

- `ESLint: Definition for rule 'import/no-import-module-exports' was not found.(import/no-import-module-exports)`
- `ESLint: Definition for rule 'import/no-relative-packages' was not found.(import/no-relative-packages)`

**Comment by kentcdodds** [comment]
Is that happening in your editor? It's possible you need to restart your editor. Those rules are definitely available if everything's installed correctly. It's just that sometimes the eslint plugins don't pick up when you reinstall dependencies.

**Comment by kentcdodds** [comment]
The original issue should be fixed now.
