### ISSUE TITLE
Remove unnecesary rules for react 17 and above

### ISSUE THREAD

**Issue by crisfcodes** [kentcdodds/eslint-config-kentcdodds#114]
According with React [documentation](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint) some rules are not neccesary, especifically: `react/jsx-uses-react` and `react/react-in-jsx-scope`, I'm having some problems with this rules in a recent project created with `create-reate-app`.

**Comment by kentcdodds** [comment]
Yeah, we should probably just disable those rules. Feel free to [make a pull request](http://makeapullrequest.com/).
