### ISSUE TITLE
Support for Newer TypeScript Versions

### ISSUE THREAD

**Issue by davidinoa** [kentcdodds/eslint-config-kentcdodds#136]
# Feature Request

## Summary:
This issue is a proposal to add support for newer versions of TypeScript (e.g., 5.x)

## Background:
Currently, `eslint-config-kentcdodds` specifies TypeScript ^4.0.0 as a peer dependency. Projects using newer TypeScript versions may encounter compatibility issues with the current version of `eslint-config-kentcdodds`.

## Proposal:
I propose updating the peerDependencies in the package.json to include TypeScript 5.x versions. This update would allow users of `eslint-config-kentcdodds` to take advantage of the latest TypeScript features while ensuring compatibility and linting effectiveness.

## Potential Challenges:

Ensuring that the existing rules and configurations are compatible with TypeScript 5.x.

## Benefits:

- Keeps `eslint-config-kentcdodds` up-to-date with the latest TypeScript developments.
- Expands the user base by supporting projects that have upgraded to TypeScript 5.x.
- Improves developer experience for those using the latest TypeScript features.

## Suggested Implementation:

Update the peerDependencies in package.json to include "typescript": ">=4.0.0 <6.0.0" (or a more appropriate version range).

If necessary, review and update configurations and rules to ensure compatibility with TypeScript 5.x.

## Looking Forward:
I am willing to help implement this feature and address any potential challenges. I look forward to hearing the community's input and guidance on this proposal.

**Comment by kentcdodds** [comment]
I'm definitely open to a pull request, but I don't use this config myself much anymore so it's hard to justify spending time working on it.
