### ISSUE TITLE
Allow ignoring unused vars in spread operator

### ISSUE THREAD

**Issue by weyert** [kentcdodds/eslint-config-kentcdodds#22]
ESlint supports the option `ignoreRestSiblings` as part of the `no-unused-vars`-rule. This flag will allow you to use something like `{ item, item2, item3, ...otherProps }` and then just use `otherProps` while ignoring the other ones. 

This would allow to drop `item`, `item2`, `item3`-fields from an existing project in a `es6` way

**Comment by kentcdodds** [comment]
PR welcome 👍

**Comment by weyert** [comment]
Done :D
