### ISSUE TITLE
In the latest release adding new rules has broken existing project pipes

### ISSUE THREAD

**Issue by jakebolam** [kentcdodds/eslint-config-kentcdodds#25]
https://github.com/kentcdodds/eslint-config-kentcdodds/commit/150a1792ca045da81f9142984620e272bf4a6bf2 has resulted in pipes breaking:
https://github.com/all-contributors/all-contributors-cli/pull/150

**Comment by kentcdodds** [comment]
Sorry about that 😬 

I think that the release of other rule changes was delayed due to the build being busted so that's why you had those issues. I typically don't concern myself too much with breaking changes in my linting config (though perhaps I should 🤔).
