### ISSUE TITLE
React version not specified in eslint-plugin-react settings

### ISSUE THREAD

**Issue by bzalasky** [kentcdodds/eslint-config-kentcdodds#26]
I switched from pretty-quick to prettier-eslint today, and noticed a warning during a pre-commit hook:

    husky > pre-commit (node v11.7.0)
    Warning: React version not specified in eslint-plugin-react settings. See 
    https://github.com/yannickcr/eslint-plugin-react#configuration .

This issue was recently fixed in eslint-plugin-react@7.12.4 (https://github.com/yannickcr/eslint-plugin-react/issues/2128), and it seems prettier-eslint is grabbing an older version from here.

**Comment by kentcdodds** [comment]
I believe this has been fixed.
