### ISSUE TITLE
If want to use this package, do I still need to install any additional plugins?

### ISSUE THREAD

**Issue by mjangir** [kentcdodds/eslint-config-kentcdodds#42]
If I want to sue this package, do I still need to install any additional plugins that you mentioned in your README.md doc like for accessibility checking? I know its being shipped with the package as those plugins are in dependencies of this package but just for shake of curiosity.

Thanks for the awesome work. I could not post it on twitter due to long text but I will wait for the reply :).

**Comment by kentcdodds** [comment]
You shouldn't have to. But be advised that this package isn't intended to be used by anyone but myself. Not to say it's not useful for others, I'm just not maintaining it for the general public. "Buyer beware." :)
