### ISSUE TITLE
Support TypeScript linting

### ISSUE THREAD

**Issue by MichaelDeBoey** [kentcdodds/eslint-config-kentcdodds#47]
Now that `kcd-scripts` supports building TypeScript (see https://github.com/kentcdodds/kcd-scripts/pull/131 & https://github.com/kentcdodds/kcd-scripts/pull/133), `eslint-config-kentcdodds` should be able to lint TypeScript (like @KubaJastrz said):
> Also, I think that `kcd-scripts lint` will fail on TypeScript files when using the default configuration. https://github.com/kentcdodds/eslint-config-kentcdodds should also be updated.

I wanted to first open this issue so we can discuss how we would handle it.

In my opinion we have 3 options:
1. Add a `kentcdodds/typescript` config, like we already have for `react`, `jest`, ...
  This is how most other configs are doing it (see [`plugin:import/typescript`](https://github.com/benmosher/eslint-plugin-import#typescript), [`prettier/@typescript-eslint`](https://github.com/prettier/eslint-config-prettier/blob/master/%40typescript-eslint.js), ...)
  This means we need to check in some way whether `react`/`jest`/... is used, because overriding rules from those configs without using them will throw an error.
2. Add `kentcdodds/react-typescript`/`kentcdodds/jest-typescript`/... configs that extend the normal configs and override the necessary rules
3. Automatically check if `typescript` is a dependency and add rule overrides in the already existing configs

I'm in favor of 2 or 3, but I'm happy to hear your thoughts @kentcdodds. 🙂

**Comment by kentcdodds** [comment]
Let's go with option 2 👍

**Comment by KubaJastrz** [comment]
What do you think about keeping all the configs and just adding overrides for TS files? Just like [`react-scripts` does this](https://github.com/facebook/create-react-app/blob/a4fa63fcc1fb97fa50778b7c1a73a01da3a3e022/packages/eslint-config-react-app/index.js#L55).

**Comment by MichaelDeBoey** [comment]
I was thinking about doing something similar like in `kcd-script` for option 3, but @KubaJastrz's idea is even better for that I think 🙂

**Comment by kentcdodds** [comment]
I'm a fan

**Comment by kentcdodds** [comment]
Note that you can't use extends with overrides

**Comment by KubaJastrz** [comment]
I think there could be a way to make this work:

> Nested `overrides` setting will be applied only if the glob patterns of both of the parent config and the child config matched. This is the same when the extended configs have `overrides` setting.
> https://eslint.org/docs/user-guide/configuring#how-it-works

**Comment by MichaelDeBoey** [comment]
Just to be sure I understand correctly: `overrides` is the same as `extends`, but for specific globs right? 🤔
You don't have a 'clean slate' when using `overrides`, right? 🤔

**Comment by kentcdodds** [comment]
Overrides does not work like extends. All rules have to be inlined and cannot reference external files. Though you can manually require and merge configs if needed. It's super annoying.

**Comment by AndrewCsontos** [comment]
> Note that you can't use extends with overrides

I believe the issue with overrides and extends in ESLint was fixed in ESLint 6. 
https://github.com/eslint/eslint/pull/11554 was released in:
https://github.com/eslint/eslint/releases/tag/v6.0.0-alpha.2

While waiting on this PR, i ended up using an overrides file for typescript that extends typescript recommended...

```
module.exports = {
  overrides: [
    {
      files: ['**/*.ts?(x)'],
      parser: '@typescript-eslint/parser',
      extends: [
        'plugin:@typescript-eslint/recommended' /* contains recommended rules and eslint-recommended to knock out eslint rules */,
        'prettier/@typescript-eslint' /* disable style rules that prettier fixes */,
      ],
...
```

**Comment by MichaelDeBoey** [comment]
@AndrewCsontos The first thing I want to do is add ESLint 7.x support and after that I'm going to look further into TypeScript support 🙂

**Comment by kentcdodds** [comment]
That would be awesome! Thank you!

**Comment by kentcdodds** [comment]
Let's revive this :) I'm building something with TypeScript right now and would love to have better linting support. I'll probably work on this sometime later if nobody gets to it before me.
