### ISSUE TITLE
package checking not woking for configs extending this one

### ISSUE THREAD

**Issue by benmonro** [kentcdodds/eslint-config-kentcdodds#65]
If i create an eslint-config that extends `kentcdodds` the package checking is going to return false (since that config won't have any of the packages)

https://github.com/kentcdodds/eslint-config-kentcdodds/blob/master/jest.js#L14-L23

i guess i can just recreate it on my side, but thought I'd share that here...

**Comment by kentcdodds** [comment]
Actually I think it should still work because read-pkg-up will look for the nearest `package.json` starting at `process.cwd()` by default (https://github.com/sindresorhus/read-pkg-up#cwd). So I think you're good to extend :)

**Comment by benmonro** [comment]
hmm ok maybe i'm doing something else wrong then, but i could swear it wasn't working for me.

**Comment by kentcdodds** [comment]
If you could dig in a little bit and let me know what you find that would be great. I definitely want to make sure this works well for folks.

**Comment by benmonro** [comment]
ok i think i have a repro, and feel free to tell me i completely borked my setup but if you clone this repo: https://github.com/benmonro/eslint-config-kcd-issue 

then `cd app && npm i` (app has installed eslint-config-my-thing which is also in the repo and installed as a link)
then `npm run lint` it will show you the config does not have the jest-dom or testing-library rules.

**Comment by kentcdodds** [comment]
I'll take a look if I find some time.

**Comment by benmonro** [comment]
yeah don't sweat it, i just defined the rules in my config but thought i'd let you know

**Comment by MichaelDeBoey** [comment]
This is fixed by #69 I guess? 🤔

**Comment by kentcdodds** [comment]
I think so. Thanks!
