### ISSUE TITLE
formly - strings must use singlequote

### ISSUE THREAD

**Issue by BarryThePenguin** [kentcdodds/eslint-config-kentcdodds#9]
Formly uses the backtick a lot. A few options
1. Change formly to use single quotes
2. Change formly to have a special rule to prefer backticks
3. Change this config to prefer backticks

I don't think there's a rule to prefer single quotes _and_ backticks

**Comment by kentcdodds** [comment]
Huh, I've never noticed issues with using single quotes when interpolation isn't needed. Do you have an example?

**Comment by BarryThePenguin** [comment]
This is an example of the problem, with the diff to fix it according to the current rules

```diff
    'fieldTransform as a function has been deprecated.',
-   `Attempted for form`,
+   'Attempted for form',
```

All the formly tests alternate between backticks and single quotes, for example

```js
    describe(`apiCheck`, () => {
      testApiCheck('setWrapper', 'getWrapper')
    })
```

**Comment by kentcdodds** [comment]
Ah, I see... Hmmm... I think my preference would be:

1. It's ok to use single quotes only if you don't have interpolation
2. It's ok to use backticks whether you have interpolation or not
3. It's never ok to use double quotes

Is there a way to configure the rules to do this? I'm pretty sure this is possible.

**Comment by BarryThePenguin** [comment]
This did work in eslint@1. There's an existing issue eslint/eslint#5234 to allow template literals alongside single/double quotes

**Comment by kentcdodds** [comment]
Ah, ok, cool. Until that gets implemented, maybe we could just have formly turn off the rule enforcing quote style.

**Comment by BarryThePenguin** [comment]
eslint/eslint#5234 is closed now. Will have to keep an eye out for when it's released

**Comment by kentcdodds** [comment]
Thanks for the ping! This is great :D bugs me all the time :-)
