### ISSUE TITLE
what are the options for <config-name>? Would I be correct if I use `kendcdodds/babel-module` in my eslintrc.js extends ?

### ISSUE THREAD

**Issue by Oluwasetemi** [kentcdodds/eslint-config-kentcdodds#93]
As stated from the picture.
![image](https://user-images.githubusercontent.com/10030028/110194299-0ad60a80-7e38-11eb-885b-40992b45561b.png)

**Comment by kentcdodds** [comment]
Hi! Sorry I missed this. You can import any of the files you see here: https://unpkg.com/browse/eslint-config-kentcdodds/

I removed `babel-module` quite a while ago and I just updated the docs. Hope that makes sense.

**Comment by Oluwasetemi** [comment]
Thanks for the response!! Thank you for the good work you do around here. I understand what I can import now.
